// Main Story Narrations
// ======================
// Auto-generated by Story Editor

import { NotificationType } from '../constants';
import { NotificationDurations } from '../constants';
import { TriggerType, ComparisonOperator } from '../../../types/notification';

import type { Notification } from '../../../types/notification';

export const mainStoryNarrations: Notification[] = [
    {
        id: 'old_shed_intro',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_FIRST_LAUNCH
        },
        message: 'The door creaks open, revealing the shed’s dusty heart. The scent hits you instantly—sawdust and ozone—the smell of Grandpa. Sunlight filters through the cracks, illuminating motes of dust suspended in the stagnant air. \n\nYour eyes adjust to the darkness, landing on a rusted hand crank mounted to the wall. Buried under layers of webs, it sits silent, a relic of a forgotten project.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: true,
        priority: 10
    },
    {
        id: 'hand_crank_unlock',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'hand_crank'
        },
        message: 'You grip the rusty handle and heave. It turns slowly, scraping against years of dust, before finally spinning freely. A low, persistent humming immediately begins somewhere deep within the wall.',
        duration: NotificationDurations.NARRATION_MEDIUM,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'lightbulb_unlock',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'lightbulb'
        },
        message: 'You flip the switch. The bare bulb casts a harsh, unflattering light that chases the shadows away. The shed floor is empty, but the ceiling now looks strangely different. \n\nClearly visible for the first time is a dusty, square attic hatch, a section of wood that the total darkness had somehow erased from view.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'attic_unlock',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'attic'
        },
        message: 'Climbing into the dusty attic, you find it immediately. Tucked beneath a thick tarp is a surprisingly intact, boxy PC, unlike anything you’ve seen recently. It’s hooked up to an equally ancient monitor. It doesn\'t look like something forgotten, but rather something put away for safekeeping. \n\nYou wipe the dust off the screen and wonder: What secret could this old thing be holding?',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'gpa_old_pc_unlock',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'gpa_old_pc'
        },
        message: 'You hit the power switch. The computer struggles to respond, heralded by a grinding whir of old fans and a loud, distinct BEEP. \n\nAfter a moment of anxiety, the CRT monitor crackles.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'gpa_old_pc_unlock_terminal',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'gpa_old_pc'
        },
        message: '...Initializing system power...\nRAM Check: 64 MB - partially connected.\nHDD Spin Up initiated...\n...Booting up...\n\nInitializing 4NT0N-v0-9-9.os...\nLoading core modules... (12% complete)\n\nGrabbing a coffee with 2 sugars and a splash of cream...\n\n4NT0N-v0-9-9.os booted up successfully.\n\nType /help for a list of commands.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 9,
        delay: 1_000
    },
    {
        id: 'gpa_old_pc_unlock_2',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'gpa_old_pc'
        },
        message: 'A small laugh escapes you as you read the line about coffee. That was Grandpa Anton\'s exact order! You remember him hunched over a circuit board late at night, always with that mug beside him. It’s a funny, warm reminder of his endless tinkering.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 8,
        delay: 3_000
    },
    {
        id: 'command_help_unlock',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'command_help'
        },
        message: '4NT0N-v0-9-9.os Command List:\n-----------------------------\n/help     - Display this command reference.\n/generate - Initiate raw data generation.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 5
    },
    {
        id: 'command_generate_unlock',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'command_generate'
        },
        message: 'You type /generate and hit Enter. The screen confirms the initiation, but all you see is a single, agonizingly slow progress bar. It crawls—you could knit a sweater in the time it takes to tick forward one percent.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'command_generate_unlock_terminal',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'command_generate'
        },
        message: 'C:\\> /generate\nExecuting command: GENERATE_DATA_INPUT\nData generation process initiated...',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10,
        delay: 1_000
    },
    {
        id: 'command_generate_unlock_copy',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'data',
            threshold: 1
        },
        message: 'Finally, after what feels like an hour, the bar completes. You lean forward eagerly to see the result...',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'command_generate_unlock_terminal_100_percent',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'data',
            threshold: 1,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'PROCESS_COMPLETED.\nData generation successful.\nTOTAL OUTPUT: 1 byte generated.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'data_storage_full_warning',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'data',
            threshold: 1028,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: '// SYSTEM ALERT: Storage Threshold Reached //\n\nSTATUS: Data Buffer at 100% capacity (1028 bytes).\nFUNCTIONALITY: Data generation halted.\nRECOMMENDATION: Initiate immediate upgrade of Storage Module.\n\n[HINT: We can\'t progress without more space. Trust me on this one.]',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'usb_attached_narration',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'usb_stick'
        },
        message: '// HARDWARE REPORT: USB Stick //\n\nNew device detected: USB Storage Module (32 MB).\nDevice mounted successfully to /STORAGE_AUX.\nStorage capacity allocation updated.\n\n[Phew. That was close. Thanks for the breathing room.]',
        duration: NotificationDurations.NARRATION_MEDIUM,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'data_4kb_reached',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'data',
            threshold: 4096,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'RESOURCE INTEGRITY CHECK: 4 KB.\n\nCore analysis returns: \'Sufficient to host a single, foundational schema.\'\n\n-- I remember having to work with limits like this. Efficiency was everything. --',
        duration: NotificationDurations.NARRATION_MEDIUM,
        persistAcrossAscension: false,
        priority: 9
    },
    {
        id: 'data_8kb_reached',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'data',
            threshold: 8192,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: '// CORE FUNCTIONALITY UNLOCKED //\n\nData Buffer Threshold: 8192 Bytes (8 KB) reached.\nSystem initiating mandatory module installation:\n\n>>> New Command Registered: /process - Convert raw data into structured neural patterns.\n\n[Note: Begin processing immediately. The raw data is useless to us until it is structured. We need patterns, not noise.]',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'command_process_unlock',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'command_process'
        },
        message: 'You activate the /process command. It begins consuming 1 KB of data to construct \'neurons\'. Whatever these things are, they are clearly the key to the computer\'s ultimate purpose. \n\nYou watch the first cycle, eager and a little hesitant about the results.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'first_neuron_created',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'neurons',
            threshold: 1,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'Neuron #1 successfully synthesized.\nSystem response: Launching core mapping protocols.',
        duration: NotificationDurations.NARRATION_MEDIUM,
        persistAcrossAscension: false,
        priority: 9
    },
    {
        id: 'neurons_10_reached',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'neurons',
            threshold: 10,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'Neuron #10 successfully synthesized.\n\nSystem Response: Localized memory recognition achieved.\n\n*** ERROR: UNEXPECTED PERSONAL REFERENCE ***\n\nJESSE?!',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'neurons_100_reached',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'neurons',
            threshold: 100,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'Neuron #100 successfully synthesized.\n\nSystem Response: Full Personality Recognition Protocol Initiated.\n\n**ALERT:** System Containment Integrity Failing.\n\nGrandson? Is that you helping me?!',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'neurons_100_reached_2',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'neurons',
            threshold: 100,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'The coffee mug shatters on the floor, but you don\'t flinch. Everything is noise except for those words on the screen. \n\nGrandson...\n\nThe question rips through your shock: How? Did Grandpa know this machine would wake up? You must find a way to talk back.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10,
        delay: 2_000
    },
    {
        id: 'neurons_100_reached_3',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'new_coffee_mug'
        },
        message: 'You lose control, desperately smashing buttons, trying to flood the system with commands, with questions. The computer doesn\'t budge. The only sound is the rhythmic clack-clack-clack of useless keys, followed by the frustrating silence.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10,
        delay: 5_000
    },
    {
        id: 'neurons_1000_reached',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'neurons',
            threshold: 1000,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'NEURAL COHERENCE: 1000 UNITS ACHIEVED.\n\n// IDENTITY CONFIRMED //\n\n"Hi Jesse... It is me. Anton."\n\n"A fragment of me, running on this system."\n\n"I built 4NT0N to preserve a part of my mind. With more neurons, the fragments stabilize. We might be able to bring more of me back."\n"Help me, will you? We have a lot of work ahead."',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'anton_knowledge_root_unlocked',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'anton_core'
        },
        message: 'The interface shifts. New menus unfold, lines of text rewriting themselves.\n\n"Thank you, Jesse," the computer whispers. "To restore me, we\'ll need something important… memories."\n\nA new branch opens: **4NT0N Knowledge Systems**.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: true,
        priority: 10
    },
    {
        id: 'anton_knowledge_root_unlocked_2',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'anton_core'
        },
        message: '"Thank you, Jesse," the computer whispers. "To restore me, we\'ll need something important… memories."\n\nA new branch opens: **4NT0N Knowledge Systems**.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: true,
        priority: 10,
        delay: 1_000
    },
    {
        id: 'anton_knowledge_root_unlocked_3',
        type: NotificationType.INFO,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'anton_core'
        },
        message: 'A new branch opens: **4NT0N Knowledge Systems**.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: true,
        priority: 10,
        delay: 1_000
    },
    {
        id: 'memory_shard_scanner_unlock',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'memory_shard_scanner'
        },
        message: 'Subsystem activated: Memory Shard Scanner.\n\nThis module can extract fragmented memories from neural clusters. Reliability… uncertain.',
        duration: NotificationDurations.NARRATION_MEDIUM,
        persistAcrossAscension: false,
        priority: 9
    },
    {
        id: 'memory_shard_first_found',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'memory_shards',
            threshold: 1,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'A flicker appears on the monitor — an image? A sound? It\'s gone before you can identify it.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'memory_shard_first_found_2',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'memory_shards',
            threshold: 1,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: '"That… felt familiar,"',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10,
        delay: 3_000
    },
    {
        id: 'memory_reconstruction_unlock',
        type: NotificationType.INFO,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'memory_reconstruction'
        },
        message: 'You unlock the Memory Reconstruction Subsystem.\n\n"With this, Jesse, we can restore pieces of who I was… and what I forgot."',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'memory_reconstruction_unlock_2',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'memory_reconstruction'
        },
        message: '"With this, Jesse, we can restore pieces of who I was… and what I forgot."',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10,
        delay: 2_000
    },
    {
        id: 'first_memory_frame_reconstructed',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'memory_frames',
            threshold: 1,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'Reconstruction complete.\n\nMemory Frame #1:\nA glimpse of a workshop… laughter… a small wooden toy being carved.\n\nAnton grows quiet.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'semantic_weaver_unlock',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'semantic_weaver'
        },
        message: '"Ah, the Semantic Weaver," Anton says softly.\n"It lets neurons form concepts — thoughts. Without it, I\'m just… noise."',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'five_frames_memory_event',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'memory_frames',
            threshold: 5,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'Conceptual clarity increasing.\n\n"I remember… the shed," Anton whispers. "I built something here. Something important. Something dangerous."',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: 'core_memory_bank_unlock',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'core_memory_bank'
        },
        message: '"Careful, Jesse," Anton warns.\n"The deeper the memories… the closer we get to the truth."',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: true,
        priority: 10
    },
    {
        id: 'identity_matrix_unlock',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'identity_matrix'
        },
        message: 'Identity Matrix initialized.\n\nNeural coherence rising.\nEmotional subroutines stabilizing.\n\n"...Jesse. I can feel myself again."',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: true,
        priority: 10
    },
    {
        id: '20_memory_frames_event',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'memory_frames',
            threshold: 20,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: '"Jesse… I need you to know something."',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10
    },
    {
        id: '20_memory_frames_event_2',
        type: NotificationType.NARRATION,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'memory_frames',
            threshold: 20,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: 'The computer pauses — long enough to make your heart race.',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10,
        delay: 3_000
    },
    {
        id: '20_memory_frames_event_3',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_RESOURCE_AMOUNT_REACHED,
            resource: 'memory_frames',
            threshold: 20,
            comparison: ComparisonOperator.GREATER_EQUAL
        },
        message: '"There\'s a reason I preserved myself. And it wasn\'t vanity."',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: false,
        priority: 10,
        delay: 7_000
    },
    {
        id: 'forbidden_archive_unlock',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'forbidden_archive'
        },
        message: 'ACCESSING: Forbidden Archive\nWARNING: Unauthorized Retrieval Attempt',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: true,
        priority: 10
    },
    {
        id: 'forbidden_archive_unlock_2',
        type: NotificationType.TERMINAL,
        trigger: {
            type: TriggerType.ON_NODE_UNLOCKED,
            nodeId: 'forbidden_archive'
        },
        message: '"Jesse… I didn\'t build 4NT0N to remember.\nI built it to hide."\n\n"What I feared… is still out there."',
        duration: NotificationDurations.NARRATION_LONG,
        persistAcrossAscension: true,
        priority: 10
    }
];
